apiVersion: batch/v1
kind: CronJob
metadata:
  name: actions-runner-offline-delete
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: delete-runners
            image: delete-runners:0.0.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python delete-runners.py
          restartPolicy: OnFailure
