apiVersion: batch/v1
kind: CronJob
metadata:
  name: runner-delete
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: delete-runners
            image: runner-delete:0.0.1
            env:
            - name: GHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github
                  key: pat
            - name: ORG_NAME
              value: "xxxx"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python delete-runners.py
          restartPolicy: OnFailure
